/* 
**  mod_logtest.c -- Apache sample logtest module
**  [Autogenerated via ``apxs -n logtest -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_logtest.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /logtest in as follows:
**
**    #   apache2.conf
**    LoadModule logtest_module modules/mod_logtest.so
**    <Location /logtest>
**    SetHandler logtest
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /logtest and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/logtest 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_logtest.c
*/ 

#include <apache2/httpd.h>
#include <apache2/http_config.h>
#include <apache2/http_protocol.h>
#include <apache2/ap_config.h>

#include "../SemanticLogger.h"
#include "../SemanticLogFileRoute.h"

/* The sample content handler */
static int logtest_handler(request_rec *r)
{
    //if (strcmp(r->handler, "logtest")) {
    //    return DECLINED;
    //}
    r->content_type = "text/html";      

	SemanticLogger log(r);
	SemanticLogRoute* route = new SemanticLogFileRoute();
	route->setLogFile("/tmp/output");
	route->setRotate(true);
	log.addRoute(route);
	log.applicationLog(1, "error\n", SemanticLogger::INFO, "aaa.aa.aaaaa", "test", "{\"ssss\":12344 }");

	std::map<std::string, std::string> itms;  // 文字×文字のmapを指定
	itms.insert(std::pair<std::string, std::string>("01", "C++"));  // 値を挿入
	itms.insert(std::pair<std::string, std::string>("02", "C#"));
	itms.insert(std::pair<std::string, std::string>("03", "VB"));
	itms.insert(std::pair<std::string, std::string>("04", "Java"));
	itms.insert(std::pair<std::string, std::string>("05", "XML"));
	log.applicationLog(2, "trace\n", SemanticLogger::TRACE, "aaa.aa.aaaaa", itms);
	log.applicationLog(3, "info\n", SemanticLogger::INFO, "aaa.aa.aaaaa");

    if (!r->header_only)
	{
        ap_rputs("The sample page from mod_logtest.c\n", r);
		ap_rprintf(r, "handler: %s", r->handler);
	}
    return OK;
}

static void logtest_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(logtest_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA logtest_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    logtest_register_hooks  /* register hooks                      */
};

